// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
//
// <auto-generated>

using System;

namespace P41.ViewBindingsGenerator
{
    /// <summary>
    /// Attribute used by the generator to generate the View.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class AndroidBindingAttribute : Attribute
    {
        /// <summary>
        /// The xml file to generate a View from.
        /// </summary>
        public string XmlFile { get; }

        /// <summary>
        /// Initialize a new <see cref="AndroidBindingAttribute"/> instance.
        /// </summary>
        /// <param name="xmlFile">The file to generate a View from.</param>
        public AndroidBindingAttribute(string xmlFile)
        {
            XmlFile = xmlFile;
        }
    }
}